### PR TITLE
Jtransform

### PR DESCRIPTION
**Pull request by ctrueden**
Updated version of PR #1.

This pull request is for an alternative version of FFTMethods that is based on jtransform instead of mines.

### CODE REVIEW

**Comment by bnorthan** [comment]
@ctrueden I added some more tests to compare mines fft with jtransform fft.  

https://github.com/imglib/imglib2-algorithm-fft/blob/jtransform/src/test/java/net/imglib2/algorithm/fft2/FFTTest.java

There are very slight differences... maybe this is something we can discuss during the upcoming hackathon??  I don't think I'll be able to make it in person but hopefully I can participate remotely.  I thought I heard @StephanPreibisch would be there... so maybe we can get his input on some of the fft related issues.

**Comment by StephanPreibisch** [comment]
Hi @bnorthan,

I originally planned to join but I am unfortunately not able to make it. I am currently rewriting my multi-view deconvolution code in ImgLib2, so I am very interested in the topic and in making the transition smooth. The multi-view deconvolution could also serve as a nice benchmark and test wether the new implementation works correctly and with acceptable performance. Maybe we could meet in New York one afternoon to finish the stuff? I will be back Jan 22nd ...

Cheers,
Stephan

**Comment by bnorthan** [comment]
Hi @StephanPreibisch 

Meeting in New York would be good.  I have also been working on FFT, kernels, and convolve/deconvolve for ops.  It would nice to be able to review that too.   Let me know what days you are available when you get back.  I am busy Tuesdays and Thursdays, but Monday, Wednesday and Fridays are ussually good for me.

**Comment by StephanPreibisch** [comment]
Hi @bnorthan,

the week after I am back should be good, sometime between the 26th and 30th, would that work for you? Let's talk details when I am back ...

Cheers, Stephan

**Comment by ctrueden** [comment]
Just to clarify the current status of this PR: it is pending joint review by @bnorthan and @StephanPreibisch when they meet in person after January 22. Please let me know if you need anything from me, guys.

**Comment by ctrueden** [comment]
Any news yet? :grin:

**Comment by bnorthan** [comment]
@StephanPreibisch any chance you are available next week on Monday Feb 2nd, Wednesday or Friday??  I can come to NY City for an afternoon.  I'd like to review this and also take a look at some of the convolve/deconvolve work in ops. 

I'd also be interested to hear about your future plans for multi-view deconvolution.  It would be nice to be able to re-use some of the code in ops.

**Comment by ctrueden** [comment]
Was there ever any decision reached about this work? I'd still love to see a switch from mines to jtransform!

**Comment by StephanPreibisch** [comment]
I now implemented the SPIM Multiview deconvolution in ImgLib2 and merged it into the code. Now we are making JUnit tests and once this is in place I am happy to change the underlying 1D-FFT code. Does that sound good?

**Comment by bnorthan** [comment]
That sounds good to me.   I've implemented a few fft related tests in imglib-algorithm-fft jtransform branch and in imagej-ops, but more testing would be ideal.   If all the SPIM Multiview deconvolution tests pass without a problem we can merge it, if there are any issues I can take a look.

**Comment by ctrueden** [comment]
@StephanPreibisch How goes it? Anything we can do to help?

**Comment by StephanPreibisch** [comment]
We still need complex Unit tests (different sizes for the FFT's and so on) that I had no time to do yet.The multiview deconvolution would be ideal choice ... we could Skype next week and decide for some way to go forward

**Comment by bnorthan** [comment]
There are some basic tests for fft in the jtransform branch.  My only concern right now is that there are slight differences between Mines and JTransform.   

https://github.com/imglib/imglib2-algorithm-fft/blob/jtransform/src/test/java/net/imglib2/algorithm/fft2/FFTTest.java

**Comment by ctrueden** [comment]
Thanks for following up, guys. Personally I will have no time to meet or discuss these changes during August, but I hope you can find a way forward, as this work is really great and would be good to get merged before the conference if possible.

**Comment by ctrueden** [comment]
I pushed a commit so that this merges cleanly again. Would still be awesome for this to get merged before the conference if possible. Or if not, we'll take care of it during the subsequent hackathon.

**Comment by ctrueden** [comment]
It is looking likely that Mines JTK will soon switch to the Apache v2 license (see dhale/jtk#12).

So we do not need to switch away from JTK anymore. However, since this work to use JTransform is complete, I am thinking it should become an alternate implementation. That way, consumers of ops could choose which routine they wish to use. We can keep JTK the default, while exposing the JTransform-based code under a different op name or namespace. What do you think, @bnorthan?

**Comment by bnorthan** [comment]
I see three options for this.

1. Simply rename the 'jtransform' version of FFTMethods and include it.  However this would mean a lot of code is repeated, but it would be easy to do. 
  
2.  Refactor FFTMethods and put the mines and jtransform specific code into a different class.  

3. Long term it could make sense to make an  ops equivalent of FFTMethods.  FFTMethods contains a lot of static signatures and some functions that loop through an ND volume and call the 1D FFT line by line.  Maybe use slicewise or a variation.  It might get a little tricky because you'd want to thread it.  You do not want to re-initialize the underlying 1D FFT each time, but you'd want a different FFT for each thread.

**Comment by StephanPreibisch** [comment]
I think it would be great to have both implementations, especially if there are slight differences. @bnorthan what kind of differences are there?

**Comment by bnorthan** [comment]
@StephanPreibisch As far as I can tell mines doesn't support power of 2 transforms (do you know why??  something to do with the underlying implementation?).  JTransform does support power of 2, and the 1D transform is faster (~20% according to my test) at power of 2.  

The drawback is that JTransform packs the complex coefficients (http://incanter.org/docs/parallelcolt/api/edu/emory/mathcs/jtransforms/fft/FloatFFT_1D.html#FloatFFT_1D(int)) so a little of logic is needed when copying back to the RandomAccess, which might cancel out the speed benefit. 

JTransform also has an API for 2D, and 3D transforms, which might be of benefit for 2D and 3D ArrayImg.  I'm not sure.  Do you find that copying takes a significant amount of time when performing ND transforms??

**Comment by ctrueden** [comment]
@StephanPreibisch @bnorthan @tpietzsch I just stumbled across this old PR again. Was a consensus ever reached regarding how to proceed?

**Comment by bnorthan** [comment]
@ctrueden after you managed to get the licensing issue with Mines sorted out this became less urgent.  It may still be nice to have it, but it would co-exist along with a Mines version, so we'd have to figure out the best way to do that.

Actually, I am not sure it still makes sense to create and maintain a JTransform version of ```FFTMethods```. 
 
Instead I think we should put effort into designing the ops/converter infrastructure to call 3rd party FFT implementations (one of which would be ```JTransform```).    Using any 3rd party FFT wrappers including native and/or GPU libraries would have the same basic workflow, 

1.  Convert from ```Imglib2``` structures, to the data structure the library needs. 
2.  Call library
3.  Convert back to ```Imglib2```

The near term effort (at least from my end) may be best focused on setting up some example and benchmark projects, that attempt to call a few different 3rd party FFT libraries (including JTransform and the GPU ones) and assess the issues involved, and understand how to design the '3rd party FFT` ops to handle many cases.

**Comment by ctrueden** [comment]
@bnorthan Sounds good. For now, shall we close this PR? For the benchmarks & comparison, perhaps that could be done in a new (experimental) repository somewhere?

**Pull request closed without merging**
